name: CI-CD-Pipeline

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: ["dev"]

jobs:
          
  deploy_stack:
    runs-on: ubuntu-latest
   # needs: [dockerize_stack_and_test_dockerized_stack]
    steps:
      - uses: actions/checkout@v3
      - name: Push to server and deploy
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          user: ${{ secrets.DEV_USERNAME }}
          port: ${{ secrets.ACCESS_PORT }}
          key: ${{ secrets.DEV_SSHKEY }}
          command: cd ${{ secrets.DEV_PATH }} && sudo docker-compose pull && sudo docker-compose up --remove-orphans
