name: Desktop Build/Release

on: 
  push:
    branches: ['dev', 'main']

jobs:
  release:
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./dekstop_frontend

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - run: echo "$PATH"
      - run: echo "./dekstop_frontend" >> $GITHUB_PATH
      - run: echo "$PATH"

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          github_token: ${{ secrets.github_token }}
          working-directory: ${{ env.working-directory }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}